In [2]:
import pandas as pd
import sqlite3 as sql
import openpyxl

avg_stats = ['AVG_QB','AVG_WR','AVG_TE','AVG_RB','AVG_DE','AVG_LB','AVG_OLB','AVG_ILB','AVG_CB','AVG_DB','AVG_S','AVG_FS','AVG_DT','AVG_K'] # List of average stats for each NFL position
total_stats = ['TOT_QB','TOT_WR','TOT_TE','TOT_RB','TOT_DE','TOT_LB','TOT_OLB','TOT_ILB','TOT_CB','TOT_DB','TOT_S','TOT_FS','TOT_DT','TOT_K'] # List of total stats """"""

In [3]:
db = sql.connect('nfl_draft_analysis.db') # Establish Database connection

xlsx = pd.ExcelFile('nfl_draft_analysis.xlsx') # Load Excel file
for sheet in avg_stats + total_stats:
    
    df = pd.read_excel(xlsx, sheet_name = sheet) # Creates a Data Frame from each Excel sheet
    df.to_sql(sheet, db, index=False, if_exists='replace') # Pushes each Data Frame as a table in the Database

Everything above this sets up the DataBase connection and tables

In [8]:
#### Things to do using SQL
# take average position stats (the important ones)
# take average career stats of each player (the ones that are most important to that position)
# compare the player stats to the average
# for stats that arent important to their position, N/A

Offensive positions

In [22]:
#QB
query_QB = """
SELECT
    t.player_name_full,
    t.position,
    t.college,
    t.draft_slot,
    t.round,
    t.pick,

    t.completions,
    a.completions_mean,
    t.completions - a.completions_mean AS completions_diff,

    t.attempts,
    a.attempts_mean,
    t.attempts - a.attempts_mean AS attempts_diff,

    t.passing_yards,
    a.passing_yards_mean,
    t.passing_yards - a.passing_yards_mean AS passing_yards_diff,

    t.passing_tds,
    a.passing_tds_mean,
    t.passing_tds - a.passing_tds_mean AS passing_tds_diff,

    t.passing_interceptions,
    a.passing_interceptions_mean,
    t.passing_interceptions - a.passing_interceptions_mean AS passing_interceptions_diff

FROM TOT_QB t
JOIN AVG_QB a
ON t.draft_slot = a.draft_slot
"""

df_qb = pd.read_sql(query_QB, db)

df_qb.head()

,player_name_full,position,college,draft_slot,round,pick,completions,completions_mean,completions_diff,attempts,...,attempts_diff,passing_yards,passing_yards_mean,passing_yards_diff,passing_tds,passing_tds_mean,passing_tds_diff,passing_interceptions,passing_interceptions_mean,passing_interceptions_diff
0,Andre Smith,QB,North Carolina,6,7,234,1349,180.05,1168.95,2044,...,1757.10,14792,2035.10,12756.90,77,11.29,65.71,33,7.19,25.81
1,Amari Rodgers,QB,Clemson,3,3,85,2910,485.78,2424.22,4512,...,3744.17,32480,5237.39,27242.61,260,31.78,228.22,56,14.11,41.89
2,Tre' Jackson,QB,Florida St.,4,4,111,4,627.56,-623.56,6,...,-970.06,37,7157.44,-7120.44,0,50.25,-50.25,0,21.56,-21.56
3,John Johnson,QB,Boston Col.,3,3,91,112,485.78,-373.78,181,...,-586.83,1255,5237.39,-3982.39,8,31.78,-23.78,6,14.11,-8.11
4,Taywan Taylor,QB,Western Kentucky,3,3,72,1035,485.78,549.22,1673,...,905.17,11639,5237.39,6401.61,65,31.78,33.22,27,14.11,12.89

In [9]:
# WR
query_WR = """
SELECT
    t.player_name_full,
    t.position,
    t.college,
    t.draft_slot,
    t.round,
    t.pick,

    t.receptions,
    a.receptions_mean,
    t.receptions - a.receptions_mean AS receptions_diff,

    t.targets,
    a.targets_mean,
    t.targets - a.targets_mean AS targets_diff,

    t.receiving_yards,
    a.receiving_yards_mean,
    t.receiving_yards - a.receiving_yards_mean AS receiving_yards_diff,

    t.receiving_tds,
    a.receiving_tds_mean,
    t.receiving_tds - a.receiving_tds_mean AS receiving_tds_diff,

    t.receiving_air_yards,
    a.receiving_air_yards_mean,
    t.receiving_air_yards - a.receiving_air_yards_mean AS receiving_air_yards_diff

FROM TOT_WR t
JOIN AVG_WR a
ON t.draft_slot = a.draft_slot
"""

df_wr = pd.read_sql(query_WR, db)
df_wr.head()

,player_name_full,position,college,draft_slot,round,pick,receptions,receptions_mean,receptions_diff,targets,...,targets_diff,receiving_yards,receiving_yards_mean,receiving_yards_diff,receiving_tds,receiving_tds_mean,receiving_tds_diff,receiving_air_yards,receiving_air_yards_mean,receiving_air_yards_diff
0,Sutton Smith,WR,Northern Illinois,6,6,175,113,59.67,53.33,169,...,71.50,1435,774.34,660.66,8,4.67,3.33,1527,1077.54,449.46
1,Austin Johnson,WR,Penn St.,2,2,43,50,136.25,-86.25,100,...,-118.71,588,1740.26,-1152.26,6,10.35,-4.35,1060,2337.48,-1277.48
2,Rachaad White,WR,Arizona St.,3,3,91,43,118.55,-75.55,70,...,-118.60,506,1541.61,-1035.61,1,9.39,-8.39,704,2107.48,-1403.48
3,Collin Johnson,WR,Texas,5,5,165,88,92.42,-4.42,149,...,2.05,1214,1196.39,17.61,9,7.58,1.42,1934,1628.47,305.53
4,Josh Jones,WR,North Carolina St.,2,2,61,0,136.25,-136.25,0,...,-218.71,0,1740.26,-1740.26,0,10.35,-10.35,0,2337.48,-2337.48

In [10]:
# RB
query_RB = """
SELECT
    t.player_name_full,
    t.position,
    t.college,
    t.draft_slot,
    t.round,
    t.pick,

    t.carries,
    a.carries_mean,
    t.carries - a.carries_mean AS carries_diff,

    t.rushing_yards,
    a.rushing_yards_mean,
    t.rushing_yards - a.rushing_yards_mean AS rushing_yards_diff,

    t.rushing_tds,
    a.rushing_tds_mean,
    t.rushing_tds - a.rushing_tds_mean AS rushing_tds_diff,

    t.receptions,
    a.receptions_mean,
    t.receptions - a.receptions_mean AS receptions_diff,

    t.targets,
    a.targets_mean,
    t.targets - a.targets_mean AS targets_diff

FROM TOT_RB t
JOIN AVG_RB a
ON t.draft_slot = a.draft_slot
"""

df_rb = pd.read_sql(query_RB, db)
df_rb.head()

,player_name_full,position,college,draft_slot,round,pick,carries,carries_mean,carries_diff,rushing_yards,...,rushing_yards_diff,rushing_tds,rushing_tds_mean,rushing_tds_diff,receptions,receptions_mean,receptions_diff,targets,targets_mean,targets_diff
0,Daryl Williams,RB,Oklahoma,4,4,102,157,216.45,-59.45,553,...,-334.78,9,5.98,3.02,33,58.80,-25.80,43,76.86,-33.86
1,Collin Johnson,RB,Texas,5,5,165,266,227.65,38.35,1023,...,58.04,4,6.31,-2.31,11,45.20,-34.20,20,59.37,-39.37
2,Andre Smith,RB,North Carolina,6,7,234,11,136.29,-125.29,58,...,-524.30,0,3.85,-3.85,6,24.97,-18.97,9,32.52,-23.52
3,Da'Ron Brown,RB,Northern Illinois,6,7,233,59,136.29,-77.29,229,...,-353.30,1,3.85,-2.85,8,24.97,-16.97,13,32.52,-19.52
4,Jaheim Bell,RB,Florida St.,6,7,231,93,136.29,-43.29,317,...,-265.30,4,3.85,0.15,23,24.97,-1.97,28,32.52,-4.52

In [11]:
#TE
query_TE = """
SELECT
    t.player_name_full,
    t.position,
    t.college,
    t.draft_slot,
    t.round,
    t.pick,

    t.receptions,
    a.receptions_mean,
    t.receptions - a.receptions_mean AS receptions_diff,

    t.targets,
    a.targets_mean,
    t.targets - a.targets_mean AS targets_diff,

    t.receiving_yards,
    a.receiving_yards_mean,
    t.receiving_yards - a.receiving_yards_mean AS receiving_yards_diff,

    t.receiving_tds,
    a.receiving_tds_mean,
    t.receiving_tds - a.receiving_tds_mean AS receiving_tds_diff,

    t.receiving_air_yards,
    a.receiving_air_yards_mean,
    t.receiving_air_yards - a.receiving_air_yards_mean AS receiving_air_yards_diff

FROM TOT_TE t
JOIN AVG_TE a
ON t.draft_slot = a.draft_slot
"""

df_te = pd.read_sql(query_TE, db)
df_te.head()

,player_name_full,position,college,draft_slot,round,pick,receptions,receptions_mean,receptions_diff,targets,...,targets_diff,receiving_yards,receiving_yards_mean,receiving_yards_diff,receiving_tds,receiving_tds_mean,receiving_tds_diff,receiving_air_yards,receiving_air_yards_mean,receiving_air_yards_diff
0,Harlan Miller,TE,Southeastern Louisiana,6,6,205,60,46.39,13.61,81,...,13.16,535,487.27,47.73,2,3.25,-1.25,465,487.59,-22.59
1,Andre Smith,TE,North Carolina,6,7,234,0,46.39,-46.39,2,...,-65.84,0,487.27,-487.27,0,3.25,-3.25,7,487.59,-480.59
2,DeMarcus Walker,TE,Florida St.,2,2,51,237,148.79,88.21,353,...,138.88,2747,1602.58,1144.42,16,12.00,4.00,3187,1552.67,1634.33
3,Michael Bennett,TE,Ohio St.,6,6,180,138,46.39,91.61,197,...,129.16,1426,487.27,938.73,10,3.25,6.75,1102,487.59,614.41
4,Khalil Davis,TE,Nebraska,6,6,194,3,46.39,-43.39,12,...,-55.84,18,487.27,-469.27,1,3.25,-2.25,92,487.59,-395.59

In [12]:
# OLB
query_OLB = """
SELECT
    t.player_name_full,
    t.position,
    t.college,
    t.draft_slot,
    t.round,
    t.pick,

    t.def_tackles_solo,
    a.def_tackles_solo_mean,
    t.def_tackles_solo - a.def_tackles_solo_mean AS def_tackles_solo_diff,

    t.def_sacks,
    a.def_sacks_mean,
    t.def_sacks - a.def_sacks_mean AS def_sacks_diff,

    t.def_qb_hits,
    a.def_qb_hits_mean,
    t.def_qb_hits - a.def_qb_hits_mean AS def_qb_hits_diff,

    t.def_interceptions,
    a.def_interceptions_mean,
    t.def_interceptions - a.def_interceptions_mean AS def_interceptions_diff,

    t.def_tackles_for_loss,
    a.def_tackles_for_loss_mean,
    t.def_tackles_for_loss - a.def_tackles_for_loss_mean AS def_tackles_for_loss_diff

FROM TOT_OLB t
JOIN AVG_OLB a
ON t.draft_slot = a.draft_slot
"""

df_olb = pd.read_sql(query_OLB, db)
df_olb.head()

,player_name_full,position,college,draft_slot,round,pick,def_tackles_solo,def_tackles_solo_mean,def_tackles_solo_diff,def_sacks,...,def_sacks_diff,def_qb_hits,def_qb_hits_mean,def_qb_hits_diff,def_interceptions,def_interceptions_mean,def_interceptions_diff,def_tackles_for_loss,def_tackles_for_loss_mean,def_tackles_for_loss_diff
0,Jarvis Harrison,OLB,Texas A&M,5,5,152,55,130.15,-75.15,13.0,...,2.54,28,25.00,3.00,2,2.31,-0.31,18,20.69,-2.69
1,D'Joun Smith,OLB,Florida Atlantic,3,3,65,68,116.62,-48.62,3.0,...,-2.69,5,13.00,-8.00,1,1.25,-0.25,7,9.75,-2.75
2,Trevor Davis,OLB,California,5,5,163,291,130.15,160.85,11.5,...,1.04,28,25.00,3.00,7,2.31,4.69,22,20.69,1.31
3,Jack Anderson,OLB,Texas Tech,6,7,236,11,164.00,-153.00,0.0,...,-11.70,1,23.67,-22.67,0,1.93,-1.93,0,22.67,-22.67
4,Davontae Harris,OLB,Illinois St.,5,5,151,133,130.15,2.85,6.5,...,-3.96,11,25.00,-14.00,0,2.31,-2.31,11,20.69,-9.69

In [13]:
# K
query_K = """
SELECT
    t.player_name_full,
    t.position,
    t.college,
    t.draft_slot,
    t.round,
    t.pick,

    t.fg_made,
    a.fg_made_mean,
    t.fg_made - a.fg_made_mean AS fg_made_diff,

    t.fg_att,
    a.fg_att_mean,
    t.fg_att - a.fg_att_mean AS fg_att_diff,

    t.fg_missed,
    a.fg_missed_mean,
    t.fg_missed - a.fg_missed_mean AS fg_missed_diff,

    t.fg_long,
    a.fg_long_mean,
    t.fg_long - a.fg_long_mean AS fg_long_diff,

    t.pat_made,
    a.pat_made_mean,
    t.pat_made - a.pat_made_mean AS pat_made_diff

FROM TOT_K t
JOIN AVG_K a
ON t.draft_slot = a.draft_slot
"""

df_k = pd.read_sql(query_K, db)
df_k.head()

,player_name_full,position,college,draft_slot,round,pick,fg_made,fg_made_mean,fg_made_diff,fg_att,...,fg_att_diff,fg_missed,fg_missed_mean,fg_missed_diff,fg_long,fg_long_mean,fg_long_diff,pat_made,pat_made_mean,pat_made_diff
0,Maxx Crosby,K,Eastern Michigan,4,4,106,188,60.20,127.80,224,...,151.00,30,10.80,19.20,4247,1378.00,2869.00,338,102.40,235.60
1,Harrison Butker,K,Georgia Tech,6,7,233,218,84.67,133.33,246,...,146.44,26,13.22,12.78,4301,1769.67,2531.33,338,130.33,207.67
2,Jake Elliott,K,Memphis,5,5,153,196,146.00,50.00,231,...,59.60,32,23.80,8.20,4252,3136.00,1116.00,318,197.60,120.40
3,Zane Gonzalez,K,Arizona St.,6,7,224,96,84.67,11.33,120,...,20.44,21,13.22,7.78,2171,1769.67,401.33,146,130.33,15.67
4,Daniel Carlson,K,Auburn,5,5,167,203,146.00,57.00,232,...,60.60,27,23.80,3.20,4171,3136.00,1035.00,223,197.60,25.40

Defensive positions

In [40]:
# FS
query_FS = """
SELECT
    t.player_name_full,
    t.position,
    t.college,
    t.draft_slot,
    t.round,
    t.pick,

    t.def_tackles_solo,
    a.def_tackles_solo_mean,
    t.def_tackles_solo - a.def_tackles_solo_mean AS def_tackles_solo_diff,

    t.def_interceptions,
    a.def_interceptions_mean,
    t.def_interceptions - a.def_interceptions_mean AS def_interceptions_diff,

    t.def_pass_defended,
    a.def_pass_defended_mean,
    t.def_pass_defended - a.def_pass_defended_mean AS def_pass_defended_diff,

    t.def_tackles_for_loss,
    a.def_tackles_for_loss_mean,
    t.def_tackles_for_loss - a.def_tackles_for_loss_mean AS def_tackles_for_loss_diff,

    t.def_qb_hits,
    a.def_qb_hits_mean,
    t.def_qb_hits - a.def_qb_hits_mean AS def_qb_hits_diff

FROM TOT_FS t
JOIN AVG_FS a
ON t.draft_slot = a.draft_slot
"""

df_fs = pd.read_sql(query_FS, db)
df_fs.head()

,player_name_full,position,college,draft_slot,round,pick,def_tackles_solo,def_tackles_solo_mean,def_tackles_solo_diff,def_interceptions,...,def_interceptions_diff,def_pass_defended,def_pass_defended_mean,def_pass_defended_diff,def_tackles_for_loss,def_tackles_for_loss_mean,def_tackles_for_loss_diff,def_qb_hits,def_qb_hits_mean,def_qb_hits_diff
0,Rondale Moore,FS,Purdue,2,2,49,10,147.29,-137.29,1,...,-4.43,2,18.57,-16.57,0,4.57,-4.57,0,1.86,-1.86
1,Tyree Wilson,FS,Texas Tech,1,1,7,231,275.00,-44.00,3,...,-6.67,13,30.83,-17.83,14,15.50,-1.50,7,9.67,-2.67
2,Jordan Richards,FS,Stanford,2,2,64,69,147.29,-78.29,0,...,-5.43,6,18.57,-12.57,0,4.57,-4.57,0,1.86,-1.86
3,Juston Burris,FS,North Carolina St.,4,4,118,117,204.00,-87.00,6,...,-2.83,20,25.83,-5.83,6,8.67,-2.67,3,2.50,0.50
4,Johnny Wilson,FS,Florida St.,6,6,185,131,136.33,-5.33,3,...,-1.17,9,13.67,-4.67,9,3.83,5.17,5,2.50,2.50

In [27]:
# DB
query_DB = """
            SELECT t.player_name_full, 
                    t.position,
                    t.college,
                    t.draft_slot,
                    t.round,
                    t.pick,

                    t.def_tackles_solo,
                    a.def_tackles_solo_mean,
                    (t.def_tackles_solo - a.def_tackles_solo_mean) AS def_tackles_diff,

                    t.def_interceptions,
                    a.def_interceptions_mean,
                    (t.def_interceptions - a.def_interceptions_mean) AS def_interceptions_diff,

                    t.def_pass_defended,
                    a.def_pass_defended_mean,
                    (t.def_pass_defended - a.def_pass_defended_mean) AS def_pass_defended_diff,
                    
                    t.def_sacks,
                    a.def_sacks_mean,
                    (t.def_sacks - a.def_sacks_mean) AS def_sacks_diff,

                    t.def_tackles_for_loss,
                    a.def_tackles_for_loss_mean,
                    (t.def_tackles_for_loss - a.def_tackles_for_loss_mean) AS def_tackles_for_loss_diff

            FROM TOT_DB t
            JOIN AVG_DB a
            ON t.draft_slot = a.draft_slot
        """
df_DB = pd.read_sql(query_DB,db)
df_DB.head()

,player_name_full,position,college,draft_slot,round,pick,def_tackles_solo,def_tackles_solo_mean,def_tackles_diff,def_interceptions,...,def_interceptions_diff,def_pass_defended,def_pass_defended_mean,def_pass_defended_diff,def_sacks,def_sacks_mean,def_sacks_diff,def_tackles_for_loss,def_tackles_for_loss_mean,def_tackles_for_loss_diff
0,Aaron Jones,DB,Texas-El Paso,5,5,182,133,54.67,78.33,6,...,4.27,26,7.20,18.80,1.0,1.10,-0.10,3,3.60,-0.60
1,Logan Hall,DB,Houston,2,2,33,96,53.13,42.87,3,...,0.20,15,9.53,5.47,2.0,0.50,1.50,3,1.80,1.20
2,Johnny Wilson,DB,Florida St.,6,6,185,24,32.25,-8.25,0,...,-0.47,1,3.58,-2.58,0.5,0.28,0.22,3,0.97,2.03
3,Spencer Brown,DB,Northern Iowa,3,3,93,32,77.31,-45.31,0,...,-2.31,2,10.06,-8.06,1.5,0.62,0.88,2,2.88,-0.88
4,Tim Williams,DB,Alabama,3,3,78,16,77.31,-61.31,1,...,-1.31,3,10.06,-7.06,0.0,0.62,-0.62,1,2.88,-1.88

In [ ]:
# CB
query_CB = """
            SELECT t.player_name_full, 
                    t.position,
                    t.college,
                    t.draft_slot,
                    t.round,
                    t.pick,

                    -- Tackles
                    t.def_tackles_solo,
                    a.def_tackles_solo_mean,
                    (t.def_tackles_solo - a.def_tackles_solo_mean) AS def_tackles_diff,

                    -- Interceptions
                    t.def_interceptions,
                    a.def_interceptions_mean,
                    (t.def_interceptions - a.def_interceptions_mean) AS def_interceptions_diff,

                    -- Pass Defended
                    t.def_pass_defended,
                    a.def_pass_defended_mean,
                    (t.def_pass_defended - a.def_pass_defended_mean) AS def_pass_defended_diff,
                    
                    -- Sacks
                    t.def_sacks,
                    a.def_sacks_mean,
                    (t.def_sacks - a.def_sacks_mean) AS def_sacks_diff,
                    
                    -- Tackles for Loss
                    t.def_tackles_for_loss,
                    a.def_tackles_for_loss_mean,
                    (t.def_tackles_for_loss - a.def_tackles_for_loss_mean) AS def_tackles_for_loss_diff

            FROM TOT_CB t
            JOIN AVG_CB a
            ON t.draft_slot = a.draft_slot

            """

df_CB = pd.read_sql(query_CB,db)
df_CB.head()

,player_name_full,position,college,draft_slot,round,pick,def_tackles_solo,def_tackles_solo_mean,def_tackles_diff,def_interceptions,...,def_interceptions_diff,def_pass_defended,def_pass_defended_mean,def_pass_defended_diff,def_sacks,def_sacks_mean,def_sacks_diff,def_tackles_for_loss,def_tackles_for_loss_mean,def_tackles_for_loss_diff
0,Cedric Tillman,CB,Tennessee,3,3,74,34,116.04,-82.04,2,...,-2.26,7,25.48,-18.48,0.0,0.63,-0.63,0,4.17,-4.17
1,Tim Williams,CB,Alabama,3,3,78,178,116.04,61.96,6,...,1.74,34,25.48,8.52,0.0,0.63,-0.63,2,4.17,-2.17
2,Trent Brown,CB,Florida,6,7,244,10,43.73,-33.73,0,...,-1.45,0,7.76,-7.76,0.0,0.26,-0.26,2,1.56,0.44
3,Tre McBride,CB,William & Mary,6,7,245,20,43.73,-23.73,3,...,1.55,4,7.76,-3.76,0.0,0.26,-0.26,1,1.56,-0.56
4,Chad Williams,CB,Grambling St.,3,3,98,29,116.04,-87.04,0,...,-4.26,4,25.48,-21.48,1.0,0.63,0.37,1,4.17,-3.17

In [ ]:
# S
query_S = """
            SELECT t.player_name_full, 
                    t.position,
                    t.college,
                    t.draft_slot,
                    t.round,
                    t.pick,

                    -- Tackles
                    t.def_tackles_solo,
                    a.def_tackles_solo_mean,
                    (t.def_tackles_solo - a.def_tackles_solo_mean) AS def_tackles_diff,

                    -- Interceptions
                    t.def_interceptions,
                    a.def_interceptions_mean,
                    (t.def_interceptions - a.def_interceptions_mean) AS def_interceptions_diff,

                    -- Pass Defended
                    t.def_pass_defended,
                    a.def_pass_defended_mean,
                    (t.def_pass_defended - a.def_pass_defended_mean) AS def_pass_defended_diff,

                    -- Tackles for Loss
                    t.def_tackles_for_loss,
                    a.def_tackles_for_loss_mean,
                    (t.def_tackles_for_loss - a.def_tackles_for_loss_mean) AS def_tackles_for_loss_diff,

                    -- QB Hits
                    t.def_qb_hits,
                    a.def_qb_hits_mean,
                    (t.def_qb_hits - a.def_qb_hits_mean) AS def_qb_hits_diff

            FROM TOT_S t
            JOIN AVG_S a
            ON t.draft_slot = a.draft_slot

            """

df_S = pd.read_sql(query_S,db)
df_S.head()

,player_name_full,position,college,draft_slot,round,pick,def_tackles_solo,def_tackles_solo_mean,def_tackles_diff,def_interceptions,...,def_interceptions_diff,def_pass_defended,def_pass_defended_mean,def_pass_defended_diff,def_tackles_for_loss,def_tackles_for_loss_mean,def_tackles_for_loss_diff,def_qb_hits,def_qb_hits_mean,def_qb_hits_diff
0,Deiondre' Hall,S,Northern Iowa,4,4,127,57,142.00,-85.00,0,...,-2.89,5,14.89,-9.89,0,4.56,-4.56,0,3.67,-3.67
1,Malcolm Mitchell,S,Georgia,4,4,112,156,142.00,14.00,5,...,2.11,21,14.89,6.11,1,4.56,-3.56,5,3.67,1.33
2,Keon Coleman,S,Florida St.,2,2,33,181,251.43,-70.43,11,...,5.43,19,20.00,-1.00,8,14.29,-6.29,4,9.14,-5.14
3,Khyree Jackson,S,Oregon,4,4,108,458,142.00,316.00,12,...,9.11,59,14.89,44.11,18,4.56,13.44,3,3.67,-0.67
4,Chris Jones,S,Mississippi St.,2,2,37,49,251.43,-202.43,3,...,-2.57,4,20.00,-16.00,1,14.29,-13.29,1,9.14,-8.14

In [35]:
# DT
query_DT = """
                SELECT t.player_name_full, 
                    t.position,
                    t.college,
                    t.draft_slot,
                    t.round,
                    t.pick,

                    -- Tackles
                    t.def_tackles_solo,
                    a.def_tackles_solo_mean,
                    (t.def_tackles_solo - a.def_tackles_solo_mean) AS def_tackles_diff,

                    -- Sacks
                    t.def_sacks,
                    a.def_sacks_mean,
                    (t.def_sacks - a.def_sacks_mean) AS def_sacks_diff,

                    -- QB Hits
                    t.def_qb_hits,
                    a.def_qb_hits_mean,
                    (t.def_qb_hits - a.def_qb_hits_mean) AS def_qb_hits_diff,

                    -- Tackles for Loss
                    t.def_tackles_for_loss,
                    a.def_tackles_for_loss_mean,
                    (t.def_tackles_for_loss - a.def_tackles_for_loss_mean) AS def_tackles_for_loss_diff,

                    -- Fumbles Forced
                    t.def_fumbles_forced,
                    a.def_fumbles_forced_mean,
                    (t.def_fumbles_forced - a.def_fumbles_forced_mean) AS def_fumbles_forced_diff
                
                FROM TOT_DT t
                JOIN AVG_DT a
                ON t.draft_slot = a.draft_slot
            
            """

df_DT = pd.read_sql(query_DT,db)
df_DT.head()

,player_name_full,position,college,draft_slot,round,pick,def_tackles_solo,def_tackles_solo_mean,def_tackles_diff,def_sacks,...,def_sacks_diff,def_qb_hits,def_qb_hits_mean,def_qb_hits_diff,def_tackles_for_loss,def_tackles_for_loss_mean,def_tackles_for_loss_diff,def_fumbles_forced,def_fumbles_forced_mean,def_fumbles_forced_diff
0,Karlos Williams,DT,Florida St.,5,5,155,15,42.03,-27.03,0.0,...,-5.07,2,15.20,-13.20,1,9.26,-8.26,2,0.80,1.20
1,David Edwards,DT,Wisconsin,5,5,169,6,42.03,-36.03,1.0,...,-4.07,3,15.20,-12.20,1,9.26,-8.26,0,0.80,-0.80
2,Taron Johnson,DT,Weber St.,4,4,121,52,39.45,12.55,12.0,...,7.34,37,12.74,24.26,20,8.58,11.42,0,0.48,-0.48
3,Karlos Williams,DT,Florida St.,5,5,155,60,42.03,17.97,13.0,...,7.93,38,15.20,22.80,18,9.26,8.74,1,0.80,0.20
4,Cole McDonald,DT,Hawaii,6,7,224,72,29.14,42.86,10.5,...,6.55,18,9.88,8.12,17,7.22,9.78,0,0.56,-0.56

In [36]:
# DE
query_DE = """
                SELECT t.player_name_full, 
                    t.position,
                    t.college,
                    t.draft_slot,
                    t.round,
                    t.pick,

                    -- Tackles
                    t.def_tackles_solo,
                    a.def_tackles_solo_mean,
                    (t.def_tackles_solo - a.def_tackles_solo_mean) AS def_tackles_diff,

                    -- Sacks
                    t.def_sacks,
                    a.def_sacks_mean,
                    (t.def_sacks - a.def_sacks_mean) AS def_sacks_diff,

                    -- QB Hits
                    t.def_qb_hits,
                    a.def_qb_hits_mean,
                    (t.def_qb_hits - a.def_qb_hits_mean) AS def_qb_hits_diff,

                    -- Tackles for Loss
                    t.def_tackles_for_loss,
                    a.def_tackles_for_loss_mean,
                    (t.def_tackles_for_loss - a.def_tackles_for_loss_mean) AS def_tackles_for_loss_diff,

                    -- Fumbles Forced
                    t.def_fumbles_forced,
                    a.def_fumbles_forced_mean,
                    (t.def_fumbles_forced - a.def_fumbles_forced_mean) AS def_fumbles_forced_diff

                FROM TOT_DE t
                JOIN AVG_DE a
                ON t.draft_slot = a.draft_slot

            """

df_DE = pd.read_sql(query_DE,db)
df_DE.head()

,player_name_full,position,college,draft_slot,round,pick,def_tackles_solo,def_tackles_solo_mean,def_tackles_diff,def_sacks,...,def_sacks_diff,def_qb_hits,def_qb_hits_mean,def_qb_hits_diff,def_tackles_for_loss,def_tackles_for_loss_mean,def_tackles_for_loss_diff,def_fumbles_forced,def_fumbles_forced_mean,def_fumbles_forced_diff
0,Jabrill Peppers,DE,Michigan,1,1,25,70,98.41,-28.41,34.0,...,3.36,55,70.91,-15.91,29,36.59,-7.59,8,6.38,1.62
1,Javorius Allen,DE,USC,4,4,125,17,50.75,-33.75,2.0,...,-9.60,16,30.36,-14.36,4,15.69,-11.69,0,1.89,-1.89
2,Andre Smith,DE,North Carolina,6,7,234,10,33.21,-23.21,3.0,...,-3.51,14,17.23,-3.23,3,9.85,-6.85,0,1.00,-1.00
3,Maxx Williams,DE,Minnesota,2,2,55,16,61.74,-45.74,4.5,...,-11.33,12,37.69,-25.69,9,19.17,-10.17,0,3.14,-3.14
4,Collin Johnson,DE,Texas,5,5,165,18,28.63,-10.63,5.0,...,-0.79,18,15.66,2.34,4,7.14,-3.14,3,1.23,1.77

In [38]:
# ILB
query = """
                SELECT t.player_name_full, 
                    t.position,
                    t.college,
                    t.draft_slot,
                    t.round,
                    t.pick,

                    -- Tackles
                    t.def_tackles_solo,
                    a.def_tackles_solo_mean,
                    (t.def_tackles_solo - a.def_tackles_solo_mean) AS def_tackles_diff,

                    -- Sacks
                    t.def_sacks,
                    a.def_sacks_mean,
                    (t.def_sacks - a.def_sacks_mean) AS def_sacks_diff,

                    -- QB Hits
                    t.def_qb_hits,
                    a.def_qb_hits_mean,
                    (t.def_qb_hits - a.def_qb_hits_mean) AS def_qb_hits_diff,

                    -- Interceptions
                    t.def_interceptions,
                    a.def_interceptions_mean,
                    (t.def_interceptions - a.def_interceptions_mean) AS def_interceptions_diff,

                    -- Tackles for Loss
                    t.def_tackles_for_loss,
                    a.def_tackles_for_loss_mean,
                    (t.def_tackles_for_loss - a.def_tackles_for_loss_mean) AS def_tackles_for_loss_diff,

                    t.def_pass_defended,
                    a.def_pass_defended_mean,
                    (t.def_pass_defended - a.def_pass_defended_mean) AS def_pass_defended_diff

                FROM TOT_ILB t
                JOIN AVG_ILB a
                ON t.draft_slot = a.draft_slot
        """

df_ILB = pd.read_sql(query,db)
df_ILB.head()

,player_name_full,position,college,draft_slot,round,pick,def_tackles_solo,def_tackles_solo_mean,def_tackles_diff,def_sacks,...,def_qb_hits_diff,def_interceptions,def_interceptions_mean,def_interceptions_diff,def_tackles_for_loss,def_tackles_for_loss_mean,def_tackles_for_loss_diff,def_pass_defended,def_pass_defended_mean,def_pass_defended_diff
0,Darius Jackson,ILB,Eastern Michigan,6,6,216,129,141.17,-12.17,4.0,...,-2.17,1,2.17,-1.17,14,11.00,3.00,13,11.83,1.17
1,Andrew Ogletree,ILB,Youngstown St.,6,6,192,321,141.17,179.83,6.0,...,11.83,9,2.17,6.83,30,11.00,19.00,39,11.83,27.17
2,Eddie Jackson,ILB,Alabama,4,4,112,47,226.38,-179.38,2.0,...,-9.62,0,2.62,-2.62,1,21.38,-20.38,0,12.62,-12.62
3,Ramik Wilson,ILB,Georgia,4,4,118,104,226.38,-122.38,0.0,...,-11.62,1,2.62,-1.62,7,21.38,-14.38,5,12.62,-7.62
4,Tyler Matakevich,ILB,Temple,6,7,246,82,141.17,-59.17,0.0,...,-8.17,1,2.17,-1.17,0,11.00,-11.00,4,11.83,-7.83

In [39]:
# LB
query = """ SELECT t.player_name_full, 
                    t.position,
                    t.college,
                    t.draft_slot,
                    t.round,
                    t.pick,

                    -- Tackles
                    t.def_tackles_solo,
                    a.def_tackles_solo_mean,
                    (t.def_tackles_solo - a.def_tackles_solo_mean) AS def_tackles_diff,

                    -- Sacks
                    t.def_sacks,
                    a.def_sacks_mean,
                    (t.def_sacks - a.def_sacks_mean) AS def_sacks_diff,

                    -- QB Hits
                    t.def_qb_hits,
                    a.def_qb_hits_mean,
                    (t.def_qb_hits - a.def_qb_hits_mean) AS def_qb_hits_diff,

                    -- Interceptions
                    t.def_interceptions,
                    a.def_interceptions_mean,
                    (t.def_interceptions - a.def_interceptions_mean) AS def_interceptions_diff,

                    -- Tackles for Loss
                    t.def_tackles_for_loss,
                    a.def_tackles_for_loss_mean,
                    (t.def_tackles_for_loss - a.def_tackles_for_loss_mean) AS def_tackles_for_loss_diff,

                    t.def_pass_defended,
                    a.def_pass_defended_mean,
                    (t.def_pass_defended - a.def_pass_defended_mean) AS def_pass_defended_diff

            FROM TOT_LB t
            JOIN AVG_LB a
            ON t.draft_slot = a.draft_slot

        """

df_LB = pd.read_sql(query,db)
df_LB.head()

,player_name_full,position,college,draft_slot,round,pick,def_tackles_solo,def_tackles_solo_mean,def_tackles_diff,def_sacks,...,def_qb_hits_diff,def_interceptions,def_interceptions_mean,def_interceptions_diff,def_tackles_for_loss,def_tackles_for_loss_mean,def_tackles_for_loss_diff,def_pass_defended,def_pass_defended_mean,def_pass_defended_diff
0,Duke Johnson,LB,Miami (FL),3,3,77,207,65.89,141.11,5.0,...,-5.21,3,0.97,2.03,17,9.79,7.21,18,4.57,13.43
1,Byron Jones,LB,Connecticut,1,1,27,4,94.07,-90.07,0.0,...,-21.45,0,0.83,-0.83,0,15.34,-15.34,0,7.21,-7.21
2,Deshaun Watson,LB,Clemson,1,1,12,23,94.07,-71.07,3.0,...,-17.45,0,0.83,-0.83,2,15.34,-13.34,0,7.21,-7.21
3,Anthony Bradford,LB,LSU,4,4,108,5,55.62,-50.62,0.0,...,-10.44,0,0.29,-0.29,0,7.09,-7.09,0,3.32,-3.32
4,John Johnson,LB,Boston Col.,3,3,91,2,65.89,-63.89,0.0,...,-12.21,0,0.97,-0.97,0,9.79,-9.79,0,4.57,-4.57