In [ ]:
import pandas as pd
import sqlite3 as sql
import openpyxl

avg_stats = ['AVG_QB','AVG_WR','AVG_TE','AVG_RB','AVG_DE','AVG_LB','AVG_OLB','AVG_ILB','AVG_CB','AVG_DB','AVG_S','AVG_FS','AVG_DT','AVG_K'] # List of average stats for each NFL position
total_stats = ['TOT_QB','TOT_WR','TOT_TE','TOT_RB','TOT_DE','TOT_LB','TOT_OLB','TOT_ILB','TOT_CB','TOT_DB','TOT_S','TOT_FS','TOT_DT','TOT_K'] # List of total stats """"""

In [ ]:
db = sql.connect('nfl_draft_analysis.db') # Establish Database connection

xlsx = pd.ExcelFile('nfl_draft_analysis.xlsx') # Load Excel file
for sheet in avg_stats + total_stats:
    
    df = pd.read_excel(xlsx, sheet_name = sheet) # Creates a Data Frame from each Excel sheet
    df.to_sql(sheet, db, index=False, if_exists='replace') # Pushes each Data Frame as a table in the Database

df_master = pd.read_excel(xlsx,sheet_name = 'MASTER_all_players') # Adds the Master table with all stats and season
df_master.to_sql('master', db, index = False, if_exists='replace')

Everything above this sets up the DataBase connection and tables

In [ ]:
#### Things to do using SQL
# take average position stats (the important ones)
# take average career stats of each player (the ones that are most important to that position)
# compare the player stats to the average
# for stats that arent important to their position, N/A

Offensive positions

In [ ]:
#QB
query_QB = """
SELECT
    t.player_name_full,
    t.position,
    t.college,
    t.draft_slot,
    t.round,
    t.pick,

    t.completions,
    a.completions_mean,
    t.completions - a.completions_mean AS completions_diff,

    t.attempts,
    a.attempts_mean,
    t.attempts - a.attempts_mean AS attempts_diff,

    t.passing_yards,
    a.passing_yards_mean,
    t.passing_yards - a.passing_yards_mean AS passing_yards_diff,

    t.passing_tds,
    a.passing_tds_mean,
    t.passing_tds - a.passing_tds_mean AS passing_tds_diff,

    t.passing_interceptions,
    a.passing_interceptions_mean,
    t.passing_interceptions - a.passing_interceptions_mean AS passing_interceptions_diff

FROM TOT_QB t
JOIN AVG_QB a
ON t.draft_slot = a.draft_slot
"""

df_qb = pd.read_sql(query_QB, db)

df_qb.head()

In [ ]:
# WR
query_WR = """
SELECT
    t.player_name_full,
    t.position,
    t.college,
    t.draft_slot,
    t.round,
    t.pick,

    t.receptions,
    a.receptions_mean,
    t.receptions - a.receptions_mean AS receptions_diff,

    t.targets,
    a.targets_mean,
    t.targets - a.targets_mean AS targets_diff,

    t.receiving_yards,
    a.receiving_yards_mean,
    t.receiving_yards - a.receiving_yards_mean AS receiving_yards_diff,

    t.receiving_tds,
    a.receiving_tds_mean,
    t.receiving_tds - a.receiving_tds_mean AS receiving_tds_diff,

    t.receiving_air_yards,
    a.receiving_air_yards_mean,
    t.receiving_air_yards - a.receiving_air_yards_mean AS receiving_air_yards_diff

FROM TOT_WR t
JOIN AVG_WR a
ON t.draft_slot = a.draft_slot
"""

df_wr = pd.read_sql(query_WR, db)
df_wr.head()

In [ ]:
# RB
query_RB = """
SELECT
    t.player_name_full,
    t.position,
    t.college,
    t.draft_slot,
    t.round,
    t.pick,

    t.carries,
    a.carries_mean,
    t.carries - a.carries_mean AS carries_diff,

    t.rushing_yards,
    a.rushing_yards_mean,
    t.rushing_yards - a.rushing_yards_mean AS rushing_yards_diff,

    t.rushing_tds,
    a.rushing_tds_mean,
    t.rushing_tds - a.rushing_tds_mean AS rushing_tds_diff,

    t.receptions,
    a.receptions_mean,
    t.receptions - a.receptions_mean AS receptions_diff,

    t.targets,
    a.targets_mean,
    t.targets - a.targets_mean AS targets_diff

FROM TOT_RB t
JOIN AVG_RB a
ON t.draft_slot = a.draft_slot
"""

df_rb = pd.read_sql(query_RB, db)
df_rb.head()

In [ ]:
#TE
query_TE = """
SELECT
    t.player_name_full,
    t.position,
    t.college,
    t.draft_slot,
    t.round,
    t.pick,

    t.receptions,
    a.receptions_mean,
    t.receptions - a.receptions_mean AS receptions_diff,

    t.targets,
    a.targets_mean,
    t.targets - a.targets_mean AS targets_diff,

    t.receiving_yards,
    a.receiving_yards_mean,
    t.receiving_yards - a.receiving_yards_mean AS receiving_yards_diff,

    t.receiving_tds,
    a.receiving_tds_mean,
    t.receiving_tds - a.receiving_tds_mean AS receiving_tds_diff,

    t.receiving_air_yards,
    a.receiving_air_yards_mean,
    t.receiving_air_yards - a.receiving_air_yards_mean AS receiving_air_yards_diff

FROM TOT_TE t
JOIN AVG_TE a
ON t.draft_slot = a.draft_slot
"""

df_te = pd.read_sql(query_TE, db)
df_te.head()

In [ ]:
# OLB
query_OLB = """
SELECT
    t.player_name_full,
    t.position,
    t.college,
    t.draft_slot,
    t.round,
    t.pick,

    t.def_tackles_solo,
    a.def_tackles_solo_mean,
    t.def_tackles_solo - a.def_tackles_solo_mean AS def_tackles_solo_diff,

    t.def_sacks,
    a.def_sacks_mean,
    t.def_sacks - a.def_sacks_mean AS def_sacks_diff,

    t.def_qb_hits,
    a.def_qb_hits_mean,
    t.def_qb_hits - a.def_qb_hits_mean AS def_qb_hits_diff,

    t.def_interceptions,
    a.def_interceptions_mean,
    t.def_interceptions - a.def_interceptions_mean AS def_interceptions_diff,

    t.def_tackles_for_loss,
    a.def_tackles_for_loss_mean,
    t.def_tackles_for_loss - a.def_tackles_for_loss_mean AS def_tackles_for_loss_diff

FROM TOT_OLB t
JOIN AVG_OLB a
ON t.draft_slot = a.draft_slot
"""

df_olb = pd.read_sql(query_OLB, db)
df_olb.head()

In [ ]:
# K
query_K = """
SELECT
    t.player_name_full,
    t.position,
    t.college,
    t.draft_slot,
    t.round,
    t.pick,

    t.fg_made,
    a.fg_made_mean,
    t.fg_made - a.fg_made_mean AS fg_made_diff,

    t.fg_att,
    a.fg_att_mean,
    t.fg_att - a.fg_att_mean AS fg_att_diff,

    t.fg_missed,
    a.fg_missed_mean,
    t.fg_missed - a.fg_missed_mean AS fg_missed_diff,

    t.fg_long,
    a.fg_long_mean,
    t.fg_long - a.fg_long_mean AS fg_long_diff,

    t.pat_made,
    a.pat_made_mean,
    t.pat_made - a.pat_made_mean AS pat_made_diff

FROM TOT_K t
JOIN AVG_K a
ON t.draft_slot = a.draft_slot
"""

df_k = pd.read_sql(query_K, db)
df_k.head()

Defensive positions

In [ ]:
# FS
query_FS = """
SELECT
    t.player_name_full,
    t.position,
    t.college,
    t.draft_slot,
    t.round,
    t.pick,

    t.def_tackles_solo,
    a.def_tackles_solo_mean,
    t.def_tackles_solo - a.def_tackles_solo_mean AS def_tackles_solo_diff,

    t.def_interceptions,
    a.def_interceptions_mean,
    t.def_interceptions - a.def_interceptions_mean AS def_interceptions_diff,

    t.def_pass_defended,
    a.def_pass_defended_mean,
    t.def_pass_defended - a.def_pass_defended_mean AS def_pass_defended_diff,

    t.def_tackles_for_loss,
    a.def_tackles_for_loss_mean,
    t.def_tackles_for_loss - a.def_tackles_for_loss_mean AS def_tackles_for_loss_diff,

    t.def_qb_hits,
    a.def_qb_hits_mean,
    t.def_qb_hits - a.def_qb_hits_mean AS def_qb_hits_diff

FROM TOT_FS t
JOIN AVG_FS a
ON t.draft_slot = a.draft_slot
"""

df_fs = pd.read_sql(query_FS, db)
df_fs.head()

In [ ]:
# DB 
query = """ SELECT t.player_name_full, 
                    t.college,
                    t.draft_slot,
                    t.round,
                    t.pick,
                    COUNT(t.player_name_full) AS num_seasons,

                    m.season,

                    -- TOTAL TACKLES
                    t.def_tackles_solo, 

                    -- TOTAL INTERCEPTIONS
                    t.def_interceptions,

                    -- TOTAL PASSES DEFENDED
                    t.def_pass_defended,

                    -- TOTAL SACKS
                    t.def_sacks,

                    -- TOTAL TACKLES FOR LOSS
                    t.def_tackles_for_loss

            FROM TOT_DB t
            JOIN master m ON m.player_id = t.player_id

            GROUP BY t.player_name_full
        """

df_DB = pd.read_sql(query,db)

,player_name_full,college,draft_slot,round,pick,num_seasons,season,def_tackles_solo,def_interceptions,def_pass_defended,def_sacks,def_tackles_for_loss
0,Aaron Jones,Texas-El Paso,5,5,182,4,2015,133,6,26,1.0,3
1,Adoree' Jackson,USC,1,1,18,3,2015,6,0,1,0.0,0
2,Ameer Speed,Michigan St.,6,6,214,1,2023,8,0,0,0.0,1
3,Andrew Thomas,Georgia,1,1,4,1,2022,3,0,0,0.0,0
4,Andru Phillips,Kentucky,3,3,70,9,2015,296,11,34,1.0,16

In [138]:
stats_to_avg = [
    'def_tackles_solo', 'def_interceptions', 'def_pass_defended',
    'def_sacks', 'def_tackles_for_loss'
]

for stat in stats_to_avg:
    new_col = stat.replace('def_', '') + '_per_season'
    df_DB[new_col] = df_DB[stat] / df_DB['num_seasons']

df_DB.head()

,player_name_full,college,draft_slot,round,pick,num_seasons,season,def_tackles_solo,def_interceptions,def_pass_defended,def_sacks,def_tackles_for_loss,tackles_solo_per_season,interceptions_per_season,pass_defended_per_season,sacks_per_season,tackles_for_loss_per_season
0,Aaron Jones,Texas-El Paso,5,5,182,4,2015,133,6,26,1.0,3,33.250000,1.500000,6.500000,0.250000,0.750000
1,Adoree' Jackson,USC,1,1,18,3,2015,6,0,1,0.0,0,2.000000,0.000000,0.333333,0.000000,0.000000
2,Ameer Speed,Michigan St.,6,6,214,1,2023,8,0,0,0.0,1,8.000000,0.000000,0.000000,0.000000,1.000000
3,Andrew Thomas,Georgia,1,1,4,1,2022,3,0,0,0.0,0,3.000000,0.000000,0.000000,0.000000,0.000000
4,Andru Phillips,Kentucky,3,3,70,9,2015,296,11,34,1.0,16,32.888889,1.222222,3.777778,0.111111,1.777778

In [ ]:
# Query CB data
query = """ SELECT t.player_name_full, 
                    t.college,
                    t.draft_slot,
                    t.round,
                    t.pick,
                    COUNT(t.player_name_full) AS num_seasons,

                    m.season,

                    -- TOTAL TACKLES
                    t.def_tackles_solo,

                    -- TOTAL INTERCEPTIONS
                    t.def_interceptions,

                    -- TOTAL PASSES DEFENDED
                    t.def_pass_defended,
                    
                    -- TOTAL SACKS
                    t.def_sacks,
                    
                    -- TOTAL TACKLES FOR LOSS
                    t.def_tackles_for_loss

            FROM TOT_CB t
            JOIN master m ON m.player_id = t.player_id

            GROUP BY t.player_name_full    
            """

df_CB = pd.read_sql(query,db)

In [134]:
stats_to_avg = [
    'def_tackles_solo', 'def_interceptions', 'def_pass_defended',
    'def_sacks', 'def_tackles_for_loss'
]

for stat in stats_to_avg:
    new_col = stat.replace('def_', '') + '_per_season'
    df_CB[new_col] = df_CB[stat] / df_CB['num_seasons']

df_CB.head()

,player_name_full,college,draft_slot,round,pick,num_seasons,season,def_tackles_solo,def_interceptions,def_pass_defended,def_sacks,def_tackles_for_loss,tackles_solo_per_season,interceptions_per_season,pass_defended_per_season,sacks_per_season,tackles_for_loss_per_season
0,A'Shawn Robinson,Alabama,2,2,46,2,2021,18,0,4,0.0,0,9.000000,0.000000,2.000000,0.0,0.000000
1,AJ Terrell,Clemson,1,1,16,5,2020,215,6,49,1.0,10,43.000000,1.200000,9.800000,0.2,2.000000
2,Adoree' Jackson,USC,1,1,18,8,2017,300,4,61,0.0,9,37.500000,0.500000,7.625000,0.0,1.125000
3,Ahkello Witherspoon,Colorado,3,3,66,8,2017,187,12,58,0.0,6,23.375000,1.500000,7.250000,0.0,0.750000
4,Akayleb Evans,Missouri,4,4,118,3,2022,62,1,10,0.0,2,20.666667,0.333333,3.333333,0.0,0.666667

In [ ]:
# S
query = """ SELECT t.player_name_full, 
                    t.college,
                    t.draft_slot,
                    t.round,
                    t.pick,
                    COUNT(t.player_name_full) AS num_seasons,

                    m.season,

                    -- TOTAL TACKLES
                    t.def_tackles_solo,

                    -- TOTAL INTERCEPTIONS
                    t.def_interceptions,

                    -- TOTAL PASSES DEFENDED
                    t.def_pass_defended,

                    -- TOTAL TACKLES FOR LOSS
                    t.def_tackles_for_loss,

                    -- TOTAL QB HITS
                    t.def_qb_hits

            FROM TOT_S t
            JOIN master m ON m.player_id = t.player_id

            GROUP BY t.player_name_full

            """

df_S = pd.read_sql(query,db)

,player_name_full,college,draft_slot,round,pick,num_seasons,season,def_tackles_solo,def_interceptions,def_pass_defended,def_tackles_for_loss,def_qb_hits
0,Adrian Amos,Penn St.,5,5,142,9,2015,505,10,50,26,9
1,Antwione Williams,Georgia Southern,5,5,169,3,2015,17,1,8,0,1
2,Budda Baker,Washington,2,2,36,8,2017,554,7,39,43,18
3,Cameron Smith,USC,5,5,162,2,2023,3,0,0,0,0
4,Chris Jones,Mississippi St.,2,2,37,5,2015,49,3,4,1,1

In [ ]:
stats_to_avg = [
    'def_tackles_solo', 'def_interceptions', 'def_pass_defended',
    'def_tackles_for_loss', 'def_qb_hits'
]

for stat in stats_to_avg:
    new_col = stat.replace('def_', '') + '_per_season'
    df_S[new_col] = df_S[stat] / df_S['num_seasons']

df_S.head()

,player_name_full,college,draft_slot,round,pick,num_seasons,season,def_tackles_solo,def_interceptions,def_pass_defended,def_tackles_for_loss,def_qb_hits,tackles_solo_per_season,interceptions_per_season,pass_defended_per_season,tackles_for_loss_per_season,qb_hits_per_season
0,Adrian Amos,Penn St.,5,5,142,9,2015,505,10,50,26,9,56.111111,1.111111,5.555556,2.888889,1.000000
1,Antwione Williams,Georgia Southern,5,5,169,3,2015,17,1,8,0,1,5.666667,0.333333,2.666667,0.000000,0.333333
2,Budda Baker,Washington,2,2,36,8,2017,554,7,39,43,18,69.250000,0.875000,4.875000,5.375000,2.250000
3,Cameron Smith,USC,5,5,162,2,2023,3,0,0,0,0,1.500000,0.000000,0.000000,0.000000,0.000000
4,Chris Jones,Mississippi St.,2,2,37,5,2015,49,3,4,1,1,9.800000,0.600000,0.800000,0.200000,0.200000
5,Clayton Geathers,Central Florida,4,4,109,5,2015,169,1,10,3,3,33.800000,0.200000,2.000000,0.600000,0.600000
6,Damarious Randall,Arizona St.,1,1,30,6,2015,234,14,47,11,3,39.000000,2.333333,7.833333,1.833333,0.500000
7,Damontae Kazee,San Diego St.,5,5,149,8,2017,233,17,24,2,0,29.125000,2.125000,3.000000,0.250000,0.000000
8,Daryl Williams,Oklahoma,4,4,102,3,2015,20,0,2,1,4,6.666667,0.000000,0.666667,0.333333,1.333333
9,Daryl Worley,West Virginia,3,3,77,9,2016,228,6,39,10,2,25.333333,0.666667,4.333333,1.111111,0.222222
10,Deiondre' Hall,Northern Iowa,4,4,127,3,2015,57,0,5,0,0,19.000000,0.000000,1.666667,0.000000,0.000000
11,Eric Murray,Minnesota,4,4,106,9,2016,245,3,24,9,9,27.222222,0.333333,2.666667,1.000000,1.000000
12,James Sample,Louisville,4,4,104,1,2015,8,0,1,1,0,8.000000,0.000000,1.000000,1.000000,0.000000
13,Jaquiski Tartt,Samford,2,2,46,7,2015,242,4,18,15,9,34.571429,0.571429,2.571429,2.142857,1.285714
14,Jayron Kearse,Clemson,6,7,244,8,2016,244,5,29,17,13,30.500000,0.625000,3.625000,2.125000,1.625000
15,Johnny Wilson,Florida St.,6,6,185,1,2015,29,1,2,1,2,29.000000,1.000000,2.000000,1.000000,2.000000
16,Jordan Lucas,Penn St.,6,6,204,4,2016,29,1,3,1,3,7.250000,0.250000,0.750000,0.250000,0.750000
17,Josh Jones,North Carolina St.,2,2,61,7,2017,169,2,9,5,4,24.142857,0.285714,1.285714,0.714286,0.571429
18,Justin Evans,Texas A&M,2,2,50,4,2017,106,4,12,4,0,26.500000,1.000000,3.000000,1.000000,0.000000
19,Justin Reid,Stanford,3,3,68,7,2018,287,8,38,13,13,41.000000,1.142857,5.428571,1.857143,1.857143
20,Keanu Neal,Florida,1,1,17,8,2016,332,4,23,19,11,41.500000,0.500000,2.875000,2.375000,1.375000
21,Ken Webster,Mississippi,6,7,252,5,2015,56,1,12,1,0,11.200000,0.200000,2.400000,0.200000,0.000000
22,Keon Coleman,Florida St.,2,2,33,5,2015,181,11,19,8,4,36.200000,2.200000,3.800000,1.600000,0.800000
23,Khari Willis,Michigan St.,4,4,109,3,2019,134,4,11,7,7,44.666667,1.333333,3.666667,2.333333,2.333333
24,Khyree Jackson,Oregon,4,4,108,10,2015,458,12,59,18,3,45.800000,1.200000,5.900000,1.800000,0.300000
25,Kyshoen Jarrett,Virginia Tech,6,6,181,1,2015,33,0,3,0,0,33.000000,0.000000,3.000000,0.000000,0.000000
26,Malcolm Mitchell,Georgia,4,4,112,4,2015,156,5,21,1,5,39.000000,1.250000,5.250000,0.250000,1.250000
27,P.J. Williams,Florida St.,3,3,78,7,2016,193,8,33,7,7,27.571429,1.142857,4.714286,1.000000,1.000000
28,Quandre Diggs,Texas,6,6,200,10,2015,427,24,56,14,5,42.700000,2.400000,5.600000,1.400000,0.500000
29,Seth Williams,Auburn,6,6,219,7,2015,291,12,26,14,14,41.571429,1.714286,3.714286,2.000000,2.000000
30,Sutton Smith,Northern Illinois,6,6,175,3,2020,3,0,0,0,0,1.000000,0.000000,0.000000,0.000000,0.000000
31,Tavius Robinson,Mississippi,4,4,124,1,2015,31,1,1,1,2,31.000000,1.000000,1.000000,1.000000,2.000000
32,Terrell Edmunds,Virginia Tech,1,1,28,9,2018,125,2,12,7,8,13.888889,0.222222,1.333333,0.777778,0.888889
33,Vonn Bell,Ohio St.,2,2,61,9,2016,459,8,39,24,28,51.000000,0.888889,4.333333,2.666667,3.111111
34,Will Parks,Arizona,6,6,219,7,2016,143,4,14,8,6,20.428571,0.571429,2.000000,1.142857,0.857143
35,Wyatt Davis,Ohio St.,3,3,86,2,2015,2,1,2,0,0,1.000000,0.500000,1.000000,0.000000,0.000000

In [ ]:
# DT
query = """ SELECT t.player_name_full, 
                    t.college,
                    t.draft_slot,
                    t.round,
                    t.pick,
                    COUNT(t.player_name_full) AS num_seasons,

                    m.season,

                    -- TOTAL TACKLES
                    t.def_tackles_solo,
                    
                    -- TOTAL SACKS
                    t.def_sacks,
                    
                    -- TOTAL QB HITS
                    t.def_qb_hits,
                   
                    -- TOTAL TACKLES FOR LOSS
                    t.def_tackles_for_loss,
                   
                    -- TOTAL FUMBLES FORCED
                    t.def_fumbles_forced
                                   
            FROM TOT_DT t
            JOIN master m ON m.player_id = t.player_id

            GROUP BY t.player_name_full

            """

df_DT = pd.read_sql(query,db)

,player_name_full,college,draft_slot,round,pick,num_seasons,season,def_tackles_solo,def_sacks,def_qb_hits,def_tackles_for_loss,def_fumbles_forced
0,Aaron Jones,Texas-El Paso,5,5,182,7,2016,15,0.0,0,1,0
1,Adetomiwa Adebawore,Northwestern,4,4,110,2,2023,8,2.5,6,4,0
2,Adolphus Washington,Ohio St.,3,3,80,3,2016,28,4.5,6,10,0
3,Alim McNeill,North Carolina St.,3,3,72,4,2021,54,11.5,27,19,2
4,Andrew Billings,Baylor,4,4,122,7,2017,76,5.5,20,20,1

In [128]:
stats_to_avg = [
    'def_tackles_solo', 'def_sacks', 'def_qb_hits', 
    'def_tackles_for_loss', 'def_fumbles_forced'
]

for stat in stats_to_avg:
    new_col = stat.replace('def_', '') + '_per_season'
    df_DT[new_col] = df_DT[stat] / df_DT['num_seasons']

df_DT.head()

,player_name_full,college,draft_slot,round,pick,num_seasons,season,def_tackles_solo,def_sacks,def_qb_hits,def_tackles_for_loss,def_fumbles_forced,tackles_solo_per_season,sacks_per_season,qb_hits_per_season,tackles_for_loss_per_season,fumbles_forced_per_season
0,Aaron Jones,Texas-El Paso,5,5,182,7,2016,15,0.0,0,1,0,2.142857,0.000000,0.000000,0.142857,0.000000
1,Adetomiwa Adebawore,Northwestern,4,4,110,2,2023,8,2.5,6,4,0,4.000000,1.250000,3.000000,2.000000,0.000000
2,Adolphus Washington,Ohio St.,3,3,80,3,2016,28,4.5,6,10,0,9.333333,1.500000,2.000000,3.333333,0.000000
3,Alim McNeill,North Carolina St.,3,3,72,4,2021,54,11.5,27,19,2,13.500000,2.875000,6.750000,4.750000,0.500000
4,Andrew Billings,Baylor,4,4,122,7,2017,76,5.5,20,20,1,10.857143,0.785714,2.857143,2.857143,0.142857

In [ ]:
# DE
query = """ SELECT t.player_name_full, 
                    t.college,
                    t.draft_slot,
                    t.round,
                    t.pick,
                    COUNT(t.player_name_full) AS num_seasons,

                    m.season,

                    -- TOTAL TACKLES
                    t.def_tackles_solo,
                    
                    -- TOTAL SACKS
                    t.def_sacks,
                  
                    -- TOTAL QB HITS
                    t.def_qb_hits,
                    
                    -- TOTAL TACKLES FOR LOSS
                    t.def_tackles_for_loss,
                    
                    -- TOTAL FUMBLES FORCED
                    t.def_fumbles_forced
                    
            FROM TOT_DE t
            JOIN master m ON m.player_id = t.player_id

            GROUP BY t.player_name_full

            """

df_DE = pd.read_sql(query,db)

,player_name_full,college,draft_slot,round,pick,num_seasons,season,def_tackles_solo,def_sacks,def_qb_hits,def_tackles_for_loss,def_fumbles_forced
0,A'Shawn Robinson,Alabama,2,2,46,9,2016,175,12.5,25,25,6
1,A.J. Epenesa,Iowa,2,2,54,5,2020,58,21.5,44,27,5
2,Aaron Jones,Texas-El Paso,5,5,182,2,2023,2,0.0,0,0,0
3,Adam Gotsis,Georgia Tech,2,2,63,9,2016,122,10.5,42,24,3
4,Aidan Hutchinson,Michigan,1,1,2,3,2022,72,28.5,65,28,4

In [125]:
stats_to_avg = [
    'def_tackles_solo', 'def_sacks', 'def_qb_hits', 
    'def_tackles_for_loss', 'def_fumbles_forced'
]

for stat in stats_to_avg:
    new_col = stat.replace('def_', '') + '_per_season'
    df_DE[new_col] = df_DE[stat] / df_DE['num_seasons']

df_DE.head()

,player_name_full,college,draft_slot,round,pick,num_seasons,season,def_tackles_solo,def_sacks,def_qb_hits,def_tackles_for_loss,def_fumbles_forced,tackles_solo_per_season,sacks_per_season,qb_hits_per_season,tackles_for_loss_per_season,fumbles_forced_per_season
0,A'Shawn Robinson,Alabama,2,2,46,9,2016,175,12.5,25,25,6,19.444444,1.388889,2.777778,2.777778,0.666667
1,A.J. Epenesa,Iowa,2,2,54,5,2020,58,21.5,44,27,5,11.600000,4.300000,8.800000,5.400000,1.000000
2,Aaron Jones,Texas-El Paso,5,5,182,2,2023,2,0.0,0,0,0,1.000000,0.000000,0.000000,0.000000,0.000000
3,Adam Gotsis,Georgia Tech,2,2,63,9,2016,122,10.5,42,24,3,13.555556,1.166667,4.666667,2.666667,0.333333
4,Aidan Hutchinson,Michigan,1,1,2,3,2022,72,28.5,65,28,4,24.000000,9.500000,21.666667,9.333333,1.333333

In [ ]:
# ILB
query = """ SELECT t.player_name_full, 
                    t.college,
                    t.draft_slot,
                    t.round,
                    t.pick,
                    COUNT(t.player_name_full) AS num_seasons,

                    m.season,

                    -- TOTAL TACKLES
                    t.def_tackles_solo,

                    -- TOTAL SACKS
                    t.def_sacks,
                    
                    -- TOTAL QB HITS
                    t.def_qb_hits,

                    -- INTERCEPTIONS
                    t.def_interceptions,

                    -- TOTAL TACKLES FOR LOSS
                    t.def_tackles_for_loss,

                    -- TOTAL PASSES DEFENDED
                    t.def_pass_defended

            FROM TOT_ILB t
            JOIN master m ON m.player_id = t.player_id

            GROUP BY t.player_name_full

        """

df_ILB = pd.read_sql(query,db)

,player_name_full,college,draft_slot,round,pick,num_seasons,season,def_tackles_solo,def_sacks,def_qb_hits,def_interceptions,def_tackles_for_loss,def_pass_defended
0,Alontae Taylor,Tennessee,2,2,49,6,2015,50,1.0,1,1,5,5
1,Andrew Ogletree,Youngstown St.,6,6,192,7,2015,321,6.0,20,9,30,39
2,Antonio Morrison,Florida,4,4,125,3,2016,121,1.0,3,0,10,1
3,Benardrick McKinney,Mississippi St.,2,2,43,7,2015,295,11.5,30,1,35,14
4,Blake Martinez,Stanford,4,4,131,8,2016,394,13.0,18,4,36,22

In [124]:
stats_to_avg = [
    'def_tackles_solo', 'def_sacks', 'def_qb_hits', 
    'def_interceptions', 'def_tackles_for_loss', 'def_pass_defended'
]

for stat in stats_to_avg:
    new_col = stat.replace('def_', '') + '_per_season'
    df_ILB[new_col] = df_ILB[stat] / df_ILB['num_seasons']

df_ILB.head()

,player_name_full,college,draft_slot,round,pick,num_seasons,season,def_tackles_solo,def_sacks,def_qb_hits,def_interceptions,def_tackles_for_loss,def_pass_defended,tackles_solo_per_season,sacks_per_season,qb_hits_per_season,interceptions_per_season,tackles_for_loss_per_season,pass_defended_per_season
0,Alontae Taylor,Tennessee,2,2,49,6,2015,50,1.0,1,1,5,5,8.333333,0.166667,0.166667,0.166667,0.833333,0.833333
1,Andrew Ogletree,Youngstown St.,6,6,192,7,2015,321,6.0,20,9,30,39,45.857143,0.857143,2.857143,1.285714,4.285714,5.571429
2,Antonio Morrison,Florida,4,4,125,3,2016,121,1.0,3,0,10,1,40.333333,0.333333,1.000000,0.000000,3.333333,0.333333
3,Benardrick McKinney,Mississippi St.,2,2,43,7,2015,295,11.5,30,1,35,14,42.142857,1.642857,4.285714,0.142857,5.000000,2.000000
4,Blake Martinez,Stanford,4,4,131,8,2016,394,13.0,18,4,36,22,49.250000,1.625000,2.250000,0.500000,4.500000,2.750000

In [ ]:
# LB
query = """ SELECT t.player_name_full, 
                    t.college,
                    t.draft_slot,
                    t.round,
                    t.pick,
                    COUNT(t.player_name_full) AS num_seasons,

                    m.season,

                    -- TOTAL TACKLES
                    t.def_tackles_solo,
                    
                    -- TOTAL SACKS
                    t.def_sacks,

                    -- TOTAL QB HITS
                    t.def_qb_hits,

                    -- TOTAL INTERCEPTIONS
                    t.def_interceptions,
                    
                    -- TOTAL TACKLES FOR LOSS
                    t.def_tackles_for_loss,

                    -- TOTAL PASSES DEFENDED
                    t.def_pass_defended

            FROM TOT_LB t
            JOIN master m ON m.player_id = t.player_id

            GROUP BY t.player_name_full
        """

df_LB = pd.read_sql(query,db)

,player_name_full,college,draft_slot,round,pick,num_seasons,season,def_tackles_solo,def_sacks,def_qb_hits,def_interceptions,def_tackles_for_loss,def_pass_defended
0,A'Shawn Robinson,Alabama,2,2,46,2,2020,18,5.0,7,0,6,1
1,Aaron Wallace,UCLA,6,7,222,3,2016,12,1.0,2,0,1,0
2,Adetokunbo Ogundeji,Notre Dame,5,5,182,3,2021,32,3.0,3,0,6,2
3,Adisa Isaac,Penn St.,3,3,93,1,2024,2,0.0,0,0,1,1
4,Akeem Davis-Gaither,Appalachian St.,4,4,107,5,2020,108,0.5,3,2,7,11

In [119]:
stats_to_avg = [
    'def_tackles_solo', 'def_sacks', 'def_qb_hits', 
    'def_interceptions', 'def_tackles_for_loss', 'def_pass_defended'
]

for stat in stats_to_avg:
    new_col = stat.replace('def_', '') + '_per_season'
    df_LB[new_col] = df_LB[stat] / df_LB['num_seasons']

df_LB # Per season stat average

,player_name_full,college,draft_slot,round,pick,num_seasons,season,def_tackles_solo,def_sacks,def_qb_hits,def_interceptions,def_tackles_for_loss,def_pass_defended,tackles_solo_per_season,sacks_per_season,qb_hits_per_season,interceptions_per_season,tackles_for_loss_per_season,pass_defended_per_season
0,A'Shawn Robinson,Alabama,2,2,46,2,2020,18,5.0,7,0,6,1,9.000000,2.500000,3.500000,0.0,3.000000,0.500000
1,Aaron Wallace,UCLA,6,7,222,3,2016,12,1.0,2,0,1,0,4.000000,0.333333,0.666667,0.0,0.333333,0.000000
2,Adetokunbo Ogundeji,Notre Dame,5,5,182,3,2021,32,3.0,3,0,6,2,10.666667,1.000000,1.000000,0.0,2.000000,0.666667
3,Adisa Isaac,Penn St.,3,3,93,1,2024,2,0.0,0,0,1,1,2.000000,0.000000,0.000000,0.0,1.000000,1.000000
4,Akeem Davis-Gaither,Appalachian St.,4,4,107,5,2020,108,0.5,3,2,7,11,21.600000,0.100000,0.600000,0.4,1.400000,2.200000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,Xavier Thomas,Clemson,5,5,138,1,2024,4,2.5,4,0,2,1,4.000000,2.500000,4.000000,0.0,2.000000,1.000000
299,YaYa Diaby,Louisville,3,3,82,2,2023,54,12.0,28,0,23,0,27.000000,6.000000,14.000000,0.0,11.500000,0.000000
300,Yasir Abdullah,Louisville,5,5,136,2,2023,13,0.0,2,0,0,0,6.500000,0.000000,1.000000,0.0,0.000000,0.000000
301,Zack Baun,Wisconsin,3,3,74,5,2020,133,5.5,13,2,16,6,26.600000,1.100000,2.600000,0.4,3.200000,1.200000
302,Zaven Collins,Tulsa,1,1,16,4,2021,109,10.5,17,2,19,13,27.250000,2.625000,4.250000,0.5,4.750000,3.250000

Get the count

In [ ]:
# Count for