In [ ]:
import pandas as pd
import sqlite3 as sql
import openpyxl

avg_stats = ['AVG_QB','AVG_WR','AVG_TE','AVG_RB','AVG_DE','AVG_LB','AVG_OLB','AVG_ILB','AVG_CB','AVG_DB','AVG_S','AVG_FS','AVG_DT','AVG_K'] # List of average stats for each NFL position
total_stats = ['TOT_QB','TOT_WR','TOT_TE','TOT_RB','TOT_DE','TOT_LB','TOT_OLB','TOT_ILB','TOT_CB','TOT_DB','TOT_S','TOT_FS','TOT_DT','TOT_K'] # List of total stats """"""

In [ ]:
db = sql.connect('nfl_draft_analysis.db') # Establish Database connection

xlsx = pd.ExcelFile('nfl_draft_analysis.xlsx') # Load Excel file
for sheet in avg_stats + total_stats:
    
    df = pd.read_excel(xlsx, sheet_name = sheet) # Creates a Data Frame from each Excel sheet
    df.to_sql(sheet, db, index=False, if_exists='replace') # Pushes each Data Frame as a table in the Database

df_master = pd.read_excel(xlsx,sheet_name = 'MASTER_all_players') # Adds the Master table with all stats and season
df_master.to_sql('master', db, index = False, if_exists='replace')

Everything above this sets up the DataBase connection and tables

In [ ]:
#### Things to do using SQL
# take average position stats (the important ones)
# take average career stats of each player (the ones that are most important to that position)
# compare the player stats to the average
# for stats that arent important to their position, N/A

Offensive positions

In [ ]:
#QB
query_QB = """
SELECT
    t.player_name_full,
    t.position,
    t.college,
    t.draft_slot,
    t.round,
    t.pick,

    t.completions,
    a.completions_mean,
    t.completions - a.completions_mean AS completions_diff,

    t.attempts,
    a.attempts_mean,
    t.attempts - a.attempts_mean AS attempts_diff,

    t.passing_yards,
    a.passing_yards_mean,
    t.passing_yards - a.passing_yards_mean AS passing_yards_diff,

    t.passing_tds,
    a.passing_tds_mean,
    t.passing_tds - a.passing_tds_mean AS passing_tds_diff,

    t.passing_interceptions,
    a.passing_interceptions_mean,
    t.passing_interceptions - a.passing_interceptions_mean AS passing_interceptions_diff

FROM TOT_QB t
JOIN AVG_QB a
ON t.draft_slot = a.draft_slot
"""

df_qb = pd.read_sql(query_QB, db)

df_qb.head()

In [ ]:
# WR
query_WR = """
SELECT
    t.player_name_full,
    t.position,
    t.college,
    t.draft_slot,
    t.round,
    t.pick,

    t.receptions,
    a.receptions_mean,
    t.receptions - a.receptions_mean AS receptions_diff,

    t.targets,
    a.targets_mean,
    t.targets - a.targets_mean AS targets_diff,

    t.receiving_yards,
    a.receiving_yards_mean,
    t.receiving_yards - a.receiving_yards_mean AS receiving_yards_diff,

    t.receiving_tds,
    a.receiving_tds_mean,
    t.receiving_tds - a.receiving_tds_mean AS receiving_tds_diff,

    t.receiving_air_yards,
    a.receiving_air_yards_mean,
    t.receiving_air_yards - a.receiving_air_yards_mean AS receiving_air_yards_diff

FROM TOT_WR t
JOIN AVG_WR a
ON t.draft_slot = a.draft_slot
"""

df_wr = pd.read_sql(query_WR, db)
df_wr.head()

In [ ]:
# RB
query_RB = """
SELECT
    t.player_name_full,
    t.position,
    t.college,
    t.draft_slot,
    t.round,
    t.pick,

    t.carries,
    a.carries_mean,
    t.carries - a.carries_mean AS carries_diff,

    t.rushing_yards,
    a.rushing_yards_mean,
    t.rushing_yards - a.rushing_yards_mean AS rushing_yards_diff,

    t.rushing_tds,
    a.rushing_tds_mean,
    t.rushing_tds - a.rushing_tds_mean AS rushing_tds_diff,

    t.receptions,
    a.receptions_mean,
    t.receptions - a.receptions_mean AS receptions_diff,

    t.targets,
    a.targets_mean,
    t.targets - a.targets_mean AS targets_diff

FROM TOT_RB t
JOIN AVG_RB a
ON t.draft_slot = a.draft_slot
"""

df_rb = pd.read_sql(query_RB, db)
df_rb.head()

In [ ]:
#TE
query_TE = """
SELECT
    t.player_name_full,
    t.position,
    t.college,
    t.draft_slot,
    t.round,
    t.pick,

    t.receptions,
    a.receptions_mean,
    t.receptions - a.receptions_mean AS receptions_diff,

    t.targets,
    a.targets_mean,
    t.targets - a.targets_mean AS targets_diff,

    t.receiving_yards,
    a.receiving_yards_mean,
    t.receiving_yards - a.receiving_yards_mean AS receiving_yards_diff,

    t.receiving_tds,
    a.receiving_tds_mean,
    t.receiving_tds - a.receiving_tds_mean AS receiving_tds_diff,

    t.receiving_air_yards,
    a.receiving_air_yards_mean,
    t.receiving_air_yards - a.receiving_air_yards_mean AS receiving_air_yards_diff

FROM TOT_TE t
JOIN AVG_TE a
ON t.draft_slot = a.draft_slot
"""

df_te = pd.read_sql(query_TE, db)
df_te.head()

In [ ]:
# OLB
query_OLB = """
SELECT
    t.player_name_full,
    t.position,
    t.college,
    t.draft_slot,
    t.round,
    t.pick,

    t.def_tackles_solo,
    a.def_tackles_solo_mean,
    t.def_tackles_solo - a.def_tackles_solo_mean AS def_tackles_solo_diff,

    t.def_sacks,
    a.def_sacks_mean,
    t.def_sacks - a.def_sacks_mean AS def_sacks_diff,

    t.def_qb_hits,
    a.def_qb_hits_mean,
    t.def_qb_hits - a.def_qb_hits_mean AS def_qb_hits_diff,

    t.def_interceptions,
    a.def_interceptions_mean,
    t.def_interceptions - a.def_interceptions_mean AS def_interceptions_diff,

    t.def_tackles_for_loss,
    a.def_tackles_for_loss_mean,
    t.def_tackles_for_loss - a.def_tackles_for_loss_mean AS def_tackles_for_loss_diff

FROM TOT_OLB t
JOIN AVG_OLB a
ON t.draft_slot = a.draft_slot
"""

df_olb = pd.read_sql(query_OLB, db)
df_olb.head()

In [ ]:
# K
query_K = """
SELECT
    t.player_name_full,
    t.position,
    t.college,
    t.draft_slot,
    t.round,
    t.pick,

    t.fg_made,
    a.fg_made_mean,
    t.fg_made - a.fg_made_mean AS fg_made_diff,

    t.fg_att,
    a.fg_att_mean,
    t.fg_att - a.fg_att_mean AS fg_att_diff,

    t.fg_missed,
    a.fg_missed_mean,
    t.fg_missed - a.fg_missed_mean AS fg_missed_diff,

    t.fg_long,
    a.fg_long_mean,
    t.fg_long - a.fg_long_mean AS fg_long_diff,

    t.pat_made,
    a.pat_made_mean,
    t.pat_made - a.pat_made_mean AS pat_made_diff

FROM TOT_K t
JOIN AVG_K a
ON t.draft_slot = a.draft_slot
"""

df_k = pd.read_sql(query_K, db)
df_k.head()

Defensive positions

In [ ]:
# FS
query_FS = """
SELECT
    t.player_name_full,
    t.position,
    t.college,
    t.draft_slot,
    t.round,
    t.pick,

    t.def_tackles_solo,
    a.def_tackles_solo_mean,
    t.def_tackles_solo - a.def_tackles_solo_mean AS def_tackles_solo_diff,

    t.def_interceptions,
    a.def_interceptions_mean,
    t.def_interceptions - a.def_interceptions_mean AS def_interceptions_diff,

    t.def_pass_defended,
    a.def_pass_defended_mean,
    t.def_pass_defended - a.def_pass_defended_mean AS def_pass_defended_diff,

    t.def_tackles_for_loss,
    a.def_tackles_for_loss_mean,
    t.def_tackles_for_loss - a.def_tackles_for_loss_mean AS def_tackles_for_loss_diff,

    t.def_qb_hits,
    a.def_qb_hits_mean,
    t.def_qb_hits - a.def_qb_hits_mean AS def_qb_hits_diff

FROM TOT_FS t
JOIN AVG_FS a
ON t.draft_slot = a.draft_slot
"""

df_fs = pd.read_sql(query_FS, db)
df_fs.head()

In [83]:
# DB 
query = """ SELECT t.player_name_full, 
                    t.college,
                    t.draft_slot,
                    t.round,
                    t.pick,

                    m.season,

                    -- TOTAL TACKLES
                    t.def_tackles_solo, 

                    -- TOTAL INTERCEPTIONS
                    t.def_interceptions,

                    -- TOTAL PASSES DEFENDED
                    t.def_pass_defended,

                    -- TOTAL SACKS
                    t.def_sacks,

                    -- TOTAL TACKLES FOR LOSS
                    t.def_tackles_for_loss

            FROM TOT_DB t
            JOIN master m ON m.player_id = t.player_id

            GROUP BY t.player_name_full
        """

df_DB = pd.read_sql(query,db)
df_DB.head()

,player_name_full,college,draft_slot,round,pick,season,def_tackles_solo,def_interceptions,def_pass_defended,def_sacks,def_tackles_for_loss
0,Aaron Jones,Texas-El Paso,5,5,182,2015,133,6,26,1.0,3
1,Adoree' Jackson,USC,1,1,18,2015,6,0,1,0.0,0
2,Ameer Speed,Michigan St.,6,6,214,2023,8,0,0,0.0,1
3,Andrew Thomas,Georgia,1,1,4,2022,3,0,0,0.0,0
4,Andru Phillips,Kentucky,3,3,70,2015,296,11,34,1.0,16

In [82]:
# CB
query = """ SELECT t.player_name_full, 
                    t.college,
                    t.draft_slot,
                    t.round,
                    t.pick,

                    m.season,

                    -- TOTAL TACKLES
                    t.def_tackles_solo,

                    -- TOTAL INTERCEPTIONS
                    t.def_interceptions,

                    -- TOTAL PASSES DEFENDED
                    t.def_pass_defended,
                    
                    -- TOTAL SACKS
                    t.def_sacks,
                    
                    -- TOTAL TACKLES FOR LOSS
                    t.def_tackles_for_loss

            FROM TOT_CB t
            JOIN master m ON m.player_id = t.player_id

            GROUP BY t.player_name_full    
            """

df_CB = pd.read_sql(query,db)
df_CB.head()

,player_name_full,college,draft_slot,round,pick,season,def_tackles_solo,def_interceptions,def_pass_defended,def_sacks,def_tackles_for_loss
0,A'Shawn Robinson,Alabama,2,2,46,2021,18,0,4,0.0,0
1,AJ Terrell,Clemson,1,1,16,2020,215,6,49,1.0,10
2,Adoree' Jackson,USC,1,1,18,2017,300,4,61,0.0,9
3,Ahkello Witherspoon,Colorado,3,3,66,2017,187,12,58,0.0,6
4,Akayleb Evans,Missouri,4,4,118,2022,62,1,10,0.0,2

In [86]:
# S
query = """ SELECT t.player_name_full, 
                    t.college,
                    t.draft_slot,
                    t.round,
                    t.pick,

                    m.season,

                    -- TOTAL TACKLES
                    t.def_tackles_solo,

                    -- TOTAL INTERCEPTIONS
                    t.def_interceptions,

                    -- TOTAL PASSES DEFENDED
                    t.def_pass_defended,

                    -- TOTAL TACKLES FOR LOSS
                    t.def_tackles_for_loss,

                    -- TOTAL QB HITS
                    t.def_qb_hits

            FROM TOT_S t
            JOIN master m ON m.player_id = t.player_id

            GROUP BY t.player_name_full

            """

df_S = pd.read_sql(query,db)
df_S.head()

,player_name_full,college,draft_slot,round,pick,season,def_tackles_solo,def_interceptions,def_pass_defended,def_tackles_for_loss,def_qb_hits
0,Adrian Amos,Penn St.,5,5,142,2015,505,10,50,26,9
1,Antwione Williams,Georgia Southern,5,5,169,2015,17,1,8,0,1
2,Budda Baker,Washington,2,2,36,2017,554,7,39,43,18
3,Cameron Smith,USC,5,5,162,2023,3,0,0,0,0
4,Chris Jones,Mississippi St.,2,2,37,2015,49,3,4,1,1

In [88]:
# DT
query = """ SELECT t.player_name_full, 
                    t.college,
                    t.draft_slot,
                    t.round,
                    t.pick,

                    m.season,

                    -- TOTAL TACKLES
                    t.def_tackles_solo,
                    
                    -- TOTAL SACKS
                    t.def_sacks,
                    
                    -- TOTAL QB HITS
                    t.def_qb_hits,
                   
                    -- TOTAL TACKLES FOR LOSS
                    t.def_tackles_for_loss,
                   
                    -- TOTAL FUMBLES FORCED
                    t.def_fumbles_forced
                                   
            FROM TOT_DT t
            JOIN master m ON m.player_id = t.player_id

            GROUP BY t.player_name_full

            """

df_DT = pd.read_sql(query,db)
df_DT.head()

,player_name_full,college,draft_slot,round,pick,season,def_tackles_solo,def_sacks,def_qb_hits,def_tackles_for_loss,def_fumbles_forced
0,Aaron Jones,Texas-El Paso,5,5,182,2016,15,0.0,0,1,0
1,Adetomiwa Adebawore,Northwestern,4,4,110,2023,8,2.5,6,4,0
2,Adolphus Washington,Ohio St.,3,3,80,2016,28,4.5,6,10,0
3,Alim McNeill,North Carolina St.,3,3,72,2021,54,11.5,27,19,2
4,Andrew Billings,Baylor,4,4,122,2017,76,5.5,20,20,1

In [89]:
# DE
query = """ SELECT t.player_name_full, 
                    t.college,
                    t.draft_slot,
                    t.round,
                    t.pick,

                    m.season,

                    -- TOTAL TACKLES
                    t.def_tackles_solo,
                    
                    -- TOTAL SACKS
                    t.def_sacks,
                  
                    -- TOTAL QB HITS
                    t.def_qb_hits,
                    
                    -- TOTAL TACKLES FOR LOSS
                    t.def_tackles_for_loss,
                    
                    -- TOTAL FUMBLES FORCED
                    t.def_fumbles_forced
                    
            FROM TOT_DE t
            JOIN master m ON m.player_id = t.player_id

            GROUP BY t.player_name_full

            """

df_DE = pd.read_sql(query,db)
df_DE.head()

,player_name_full,college,draft_slot,round,pick,season,def_tackles_solo,def_sacks,def_qb_hits,def_tackles_for_loss,def_fumbles_forced
0,A'Shawn Robinson,Alabama,2,2,46,2016,175,12.5,25,25,6
1,A.J. Epenesa,Iowa,2,2,54,2020,58,21.5,44,27,5
2,Aaron Jones,Texas-El Paso,5,5,182,2023,2,0.0,0,0,0
3,Adam Gotsis,Georgia Tech,2,2,63,2016,122,10.5,42,24,3
4,Aidan Hutchinson,Michigan,1,1,2,2022,72,28.5,65,28,4

In [92]:
# ILB
query = """ SELECT t.player_name_full, 
                    t.college,
                    t.draft_slot,
                    t.round,
                    t.pick,

                    m.season,

                    -- TOTAL TACKLES
                    t.def_tackles_solo,

                    -- TOTAL SACKS
                    t.def_sacks,
                    
                    -- TOTAL QB HITS
                    t.def_qb_hits,

                    -- INTERCEPTIONS
                    t.def_interceptions,

                    -- TOTAL TACKLES FOR LOSS
                    t.def_tackles_for_loss,

                    -- TOTAL PASSES DEFENDED
                    t.def_pass_defended

            FROM TOT_ILB t
            JOIN master m ON m.player_id = t.player_id

            GROUP BY t.player_name_full

        """

df_ILB = pd.read_sql(query,db)
df_ILB.head()

,player_name_full,college,draft_slot,round,pick,season,def_tackles_solo,def_sacks,def_qb_hits,def_interceptions,def_tackles_for_loss,def_pass_defended
0,Alontae Taylor,Tennessee,2,2,49,2015,50,1.0,1,1,5,5
1,Andrew Ogletree,Youngstown St.,6,6,192,2015,321,6.0,20,9,30,39
2,Antonio Morrison,Florida,4,4,125,2016,121,1.0,3,0,10,1
3,Benardrick McKinney,Mississippi St.,2,2,43,2015,295,11.5,30,1,35,14
4,Blake Martinez,Stanford,4,4,131,2016,394,13.0,18,4,36,22

In [99]:
# LB
query = """ SELECT t.player_name_full, 
                    t.college,
                    t.draft_slot,
                    t.round,
                    t.pick,

                    m.season,

                    -- TOTAL TACKLES
                    t.def_tackles_solo,
                    
                    -- TOTAL SACKS
                    t.def_sacks,

                    -- TOTAL QB HITS
                    t.def_qb_hits,

                    -- TOTAL INTERCEPTIONS
                    t.def_interceptions,
                    
                    -- TOTAL TACKLES FOR LOSS
                    t.def_tackles_for_loss,

                    -- TOTAL PASSES DEFENDED
                    t.def_pass_defended

            FROM TOT_LB t
            JOIN master m ON m.player_id = t.player_id

            GROUP BY t.player_name_full
        """

df_LB = pd.read_sql(query,db)
df_LB.head()

,player_name_full,college,draft_slot,round,pick,season,def_tackles_solo,def_sacks,def_qb_hits,def_interceptions,def_tackles_for_loss,def_pass_defended
0,A'Shawn Robinson,Alabama,2,2,46,2020,18,5.0,7,0,6,1
1,Aaron Wallace,UCLA,6,7,222,2016,12,1.0,2,0,1,0
2,Adetokunbo Ogundeji,Notre Dame,5,5,182,2021,32,3.0,3,0,6,2
3,Adisa Isaac,Penn St.,3,3,93,2024,2,0.0,0,0,1,1
4,Akeem Davis-Gaither,Appalachian St.,4,4,107,2020,108,0.5,3,2,7,11

Get the count

In [ ]:
# Count for